//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asset_and_Maintenance_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public System.DateTime loginTime { get; set; }
        public string username { get; set; }
        public string category { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
