//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asset_and_Maintenance_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonCurrentAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NonCurrentAsset()
        {
            this.WorkerReports = new HashSet<WorkerReport>();
            this.Disposals = new HashSet<Disposal>();
        }
    
        public string asset_id { get; set; }
        public Nullable<byte> lifetime { get; set; }
        public Nullable<decimal> depreciationRate { get; set; }
        public string condition { get; set; }
        public string manufacturer { get; set; }
        public string plant { get; set; }
        public string serialNumber { get; set; }
        public string depreciationMethod { get; set; }
        public decimal costOfPurchase { get; set; }
        public Nullable<decimal> serviceInterval { get; set; }
        public Nullable<decimal> currentMarketValue { get; set; }
        public string warranty { get; set; }
        public string state { get; set; }
        public Nullable<decimal> disposalValue { get; set; }
        public string assetType { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public string warrantyCode { get; set; }
        public Nullable<System.DateTime> serviceDue { get; set; }
        public Nullable<System.DateTime> disposalDate { get; set; }
    
        public virtual Warranty Warranty1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkerReport> WorkerReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disposal> Disposals { get; set; }
    }
}
