//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asset_and_Maintenance_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerReport
    {
        public string username { get; set; }
        public System.DateTime reported_date { get; set; }
        public string asset_id { get; set; }
        public string plant { get; set; }
        public string criticality_machineOperations { get; set; }
        public string criticality_activityConstraints { get; set; }
        public bool managerRespoded { get; set; }
        public Nullable<System.DateTime> service_date_schedule { get; set; }
        public string message { get; set; }
    
        public virtual NonCurrentAsset NonCurrentAsset { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
